### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by abanusara99** [budlebee/videoglancer#1]
i saw a few videos about your creation. i tried to down 22:00 duration video, 30 seconds video and 1 hour video.

i saw errors like this

1 - Error. Check url. (we cannot support video under 1 minute)

2- Something went wrong:

Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
<button>Try again</button>

please check carefully

**Comment by budlebee** [comment]
I shut down videoglancer's functions because there are cost and time issues. Videoglancer may will revive, but not soon.
